version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql_data
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql